/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _AbsoluteTimerInstruction(ManagementObject ManagementObject) : _TimerInstruction(ManagementObject)
{
    /// <summary>
    /// Fixed-length string in DMTF format that specifies when the timer fires.
    /// </summary>
    public DateTimeOffset? EventDateTime => ManagementObject.GetDateTimePropertyValue(nameof(EventDateTime));
}
