/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _ACE(ManagementObject ManagementObject) : _SecurityRelatedClass(ManagementObject)
{
    /// <summary>
    /// The time, in the CIM_DATETIME format, when the security descriptor was created.
    /// </summary>
    public ulong? TIME_CREATED => (ulong?)ManagementObject[nameof(TIME_CREATED)];
    /// <summary>
    /// The trustee of the ACE entry represented by this instance of the __ACE class.
    /// </summary>
    public _Trustee? Trustee => (_Trustee)ManagementObject[nameof(Trustee)];
}
