/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _AggregateEvent(ManagementObject ManagementObject) : _IndicationRelated(ManagementObject)
{
    /// <summary>
    /// Number of events combined to produce this single summary event.
    /// </summary>
    public uint? NumberOfEvents => (uint?)ManagementObject[nameof(NumberOfEvents)];
    /// <summary>
    /// Copy of one of the events delivered within the aggregation interval. For example, if a consumer has registered for registry key change events from the Registry Event provider, Representative would hold an instance of the RegistryKeyChangeEvent class.
    /// </summary>
    public object? Representative => (object)ManagementObject[nameof(Representative)];
}
