/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _ClassModificationEvent(ManagementObject ManagementObject) : _ClassOperationEvent(ManagementObject)
{
    /// <summary>
    /// Copy of the original version of the class.
    /// </summary>
    public object? PreviousClass => (object)ManagementObject[nameof(PreviousClass)];
}
