/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _ClassOperationEvent(ManagementObject ManagementObject) : _Event(ManagementObject)
{
    /// <summary>
    /// Class affected by the event. For creation events, this is the newly created class. For modification events, this is the new version of the changed class. For deletion events, this is the deleted class.
    /// </summary>
    public object? TargetClass => (object)ManagementObject[nameof(TargetClass)];
}
