/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _ClassProviderRegistration(ManagementObject ManagementObject) : _ObjectProviderRegistration(ManagementObject)
{
    /// <summary>
    /// Not used.
    /// </summary>
    public DateTimeOffset? CacheRefreshInterval => ManagementObject.GetDateTimePropertyValue(nameof(CacheRefreshInterval));
    /// <summary>
    /// Not used.
    /// </summary>
    public bool? PerUserSchema => (bool?)ManagementObject[nameof(PerUserSchema)];
    /// <summary>
    /// One or more queries that describe the set of referenced classes that a class provider supports. Providers that can supply association classes must include at least one query in this property.
    /// </summary>
    public string[]? ReferencedSetQueries => (string[])ManagementObject[nameof(ReferencedSetQueries)];
    /// <summary>
    /// One or more queries that describe the set of all classes that can be supplied by the class provider, or a superset of those classes. This property never specifies a subset of supported classes.
    /// </summary>
    public string[]? ResultSetQueries => (string[])ManagementObject[nameof(ResultSetQueries)];
    /// <summary>
    /// Not used.
    /// </summary>
    public bool? ReSynchroniseOnNamespaceOpen => (bool?)ManagementObject[nameof(ReSynchroniseOnNamespaceOpen)];
    /// <summary>
    /// Not used.
    /// </summary>
    public bool? SuppportsBatching => (bool?)ManagementObject[nameof(SuppportsBatching)];
    /// <summary>
    /// One or more queries that describe the set of classes that the class provider does not support. Use this property to subtract from the set of classes implied by ResultSetQueries.
    /// </summary>
    public string[]? UnsupportedQueries => (string[])ManagementObject[nameof(UnsupportedQueries)];
    /// <summary>
    /// Version of this class provider.
    /// </summary>
    public uint? Version => (uint?)ManagementObject[nameof(Version)];
}
