/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _ConsumerFailureEvent(ManagementObject ManagementObject) : _EventDroppedEvent(ManagementObject)
{
    /// <summary>
    /// Error code returned by the consumer.
    /// </summary>
    public uint? ErrorCode => (uint?)ManagementObject[nameof(ErrorCode)];
    /// <summary>
    /// Extended error code description, if available.
    /// </summary>
    public string? ErrorDescription => (string)ManagementObject[nameof(ErrorDescription)];
    /// <summary>
    /// Object in error.
    /// </summary>
    public object? ErrorObject => (object)ManagementObject[nameof(ErrorObject)];
}
