/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _EventConsumer(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Security identifier (SID) that uniquely identifies the user who creates a filter. WMI stores the SID of the user who creates an instance of __EventConsumer or the Administrator SID, depending on the operating system. For more information, see Binding an Event Filter with a Logical Consumer and Monitoring and Responding to Events with Standard Consumers.
    /// </summary>
    public byte[]? CreatorSID => (byte[])ManagementObject[nameof(CreatorSID)];
    /// <summary>
    /// Name of the computer to which Windows Management Instrumentation (WMI) sends events.
    /// </summary>
    public string? MachineName => (string)ManagementObject[nameof(MachineName)];
    /// <summary>
    /// Maximum queue for a specific consumer, in bytes.
    /// </summary>
    public uint? MaximumQueueSize => (uint?)ManagementObject[nameof(MaximumQueueSize)];
}
