/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _EventDroppedEvent(ManagementObject ManagementObject) : _SystemEvent(ManagementObject)
{
    /// <summary>
    /// Event that is dropped.
    /// </summary>
    public _Event? Event => (_Event)ManagementObject[nameof(Event)];
    /// <summary>
    /// Reference to an instance of __EventConsumer that represents the permanent consumer you identify to receive an event. Different permanent consumers that subscribe to an event can continue to receive the event.
    /// </summary>
    public _EventConsumer? IntendedConsumer => (_EventConsumer)ManagementObject[nameof(IntendedConsumer)];
}
