/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _ExtrinsicEvent(ManagementObject ManagementObject) : _Event(ManagementObject)
{
}
