/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _ExtendedStatus(ManagementObject ManagementObject) : _NotifyStatus(ManagementObject)
{
    /// <summary>
    /// Any user-defined string that describes an error or operational status.
    /// </summary>
    public string? Description => (string)ManagementObject[nameof(Description)];
    public string? Operation => (string)ManagementObject[nameof(Operation)];
    /// <summary>
    /// Parameters involved in an error or status change. For example, if an application attempts to retrieve a class that does not exist, this property is set to the offending class name.
    /// </summary>
    public string? ParameterInfo => (string)ManagementObject[nameof(ParameterInfo)];
    /// <summary>
    /// Identifies the provider that causes or reports an error or status change. If a provider is not involved, this string is set to "Windows Management".
    /// </summary>
    public string? ProviderName => (string)ManagementObject[nameof(ProviderName)];
}
