/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _FilterToConsumerBinding(ManagementObject ManagementObject) : _IndicationRelated(ManagementObject)
{
    /// <summary>
    /// Reference to an instance of __EventConsumer that represents the object path to a logical consumer, the recipient of an event. A logical consumer is an instance of a class derived from __EventConsumer.
    /// </summary>
    public _EventConsumer? Consumer => (_EventConsumer)ManagementObject[nameof(Consumer)];
    /// <summary>
    /// Security identifier (SID) that uniquely identifies the user who created the binding. Depending on the operating system, WMI stores the Administrator SID or the SID of the user that creates an instance of __FilterToConsumerBinding. For more information, see Binding an Event Filter with a Logical Consumer and Monitoring and Responding to Events with Standard Consumers.
    /// </summary>
    public byte[]? CreatorSID => (byte[])ManagementObject[nameof(CreatorSID)];
    /// <summary>
    /// Obsolete. Instead use the DeliveryQoS property in place of this property, because if DeliverSynchronously is set to True it overrides the setting of the DeliveryQoS property.
    /// </summary>
    public bool? DeliverSynchronously => (bool?)ManagementObject[nameof(DeliverSynchronously)];
    /// <summary>
    /// Quality of service for a subscription. If the DeliverSynchronously property is set to True, it overrides the setting of the DeliveryQoS property.
    /// </summary>
    public uint? DeliveryQoS => (uint?)ManagementObject[nameof(DeliveryQoS)];
    /// <summary>
    /// Reference to an instance of __EventFilter that represents the object path to an event filter which is a query that specifies the type of event to be received.
    /// </summary>
    public _EventFilter? Filter => (_EventFilter)ManagementObject[nameof(Filter)];
    /// <summary>
    /// If True, the events are delivered in the same security context that the provider was in when it provided them.
    /// </summary>
    public bool? MaintainSecurityContext => (bool?)ManagementObject[nameof(MaintainSecurityContext)];
    /// <summary>
    /// If True, providers are slowed down if this consumer cannot keep up.
    /// </summary>
    public bool? SlowDownProviders => (bool?)ManagementObject[nameof(SlowDownProviders)];
}
