/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _IntervalTimerInstruction(ManagementObject ManagementObject) : _TimerInstruction(ManagementObject)
{
    /// <summary>
    /// Number of milliseconds between event firings.
    /// </summary>
    public uint? IntervalBetweenEvents => (uint?)ManagementObject[nameof(IntervalBetweenEvents)];
}
