/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _MethodInvocationEvent(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Method invoked to trigger the event.
    /// </summary>
    public string? Method => (string)ManagementObject[nameof(Method)];
    /// <summary>
    /// Reference to an instance that represents the input and output parameters of the method call.
    /// </summary>
    public _Parameters? Parameters => (_Parameters)ManagementObject[nameof(Parameters)];
    /// <summary>
    /// If TRUE, the event is raised before the method is called.
    /// </summary>
    public bool? PreCall => (bool?)ManagementObject[nameof(PreCall)];
}
