/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _Namespace(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Namespace name.
    /// </summary>
    public string? Name => (string)ManagementObject[nameof(Name)];
}
