/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _NotifyStatus(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Contains an error or information code for an operation. This can be any user-defined code, but the value 0 (zero) is usually reserved to indicate success.
    /// </summary>
    public uint? StatusCode => (uint?)ManagementObject[nameof(StatusCode)];
}
