/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _NTLMUser9X(ManagementObject ManagementObject) : _SecurityRelatedClass(ManagementObject)
{
    /// <summary>
    /// Domain to which a user name applies.
    /// </summary>
    public string? Authority => (string)ManagementObject[nameof(Authority)];
    /// <summary>
    /// Inheritance flags.
    /// </summary>
    public int? Flags => (int?)ManagementObject[nameof(Flags)];
    /// <summary>
    /// Bitmask that specifies access rights to the namespace in the Windows Management Instrumentation (WMI) repository. For bit values, see Namespace Access Rights Constants.
    /// </summary>
    public int? Mask => (int?)ManagementObject[nameof(Mask)];
    /// <summary>
    /// User name.
    /// </summary>
    public string? Name => (string)ManagementObject[nameof(Name)];
    /// <summary>
    /// Access allowed.
    /// </summary>
    public int? Type => (int?)ManagementObject[nameof(Type)];
}
