/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _ObjectProviderCacheControl(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Time interval after which WMI releases an instance, class, or method provider. The time is in interval format.
    /// </summary>
    public DateTimeOffset? ClearAfter => ManagementObject.GetDateTimePropertyValue(nameof(ClearAfter));
}
