/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _ProviderRegistration(ManagementObject ManagementObject) : _SystemClass(ManagementObject)
{
    /// <summary>
    /// Reference to an instance of __Provider representing the object path to the provider.
    /// </summary>
    public _Provider? provider => (_Provider)ManagementObject[nameof(provider)];
}
