/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _PropertyProviderCacheControl(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Time interval after WMI releases a property provider. The time is in the interval format.
    /// </summary>
    public DateTimeOffset? ClearAfter => ManagementObject.GetDateTimePropertyValue(nameof(ClearAfter));
}
