/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _SecurityDescriptor(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Bit flags that provide information about the descriptor's contents and format. See the ControlFlags property in the Win32_SecurityDescriptor class for a description of the flags.
    /// </summary>
    public uint? ControlFlags => (uint?)ManagementObject[nameof(ControlFlags)];
    /// <summary>
    /// An array of __ACE entries that specify access to the object.
    /// </summary>
    public _Object[]? DACL => (_Object[])ManagementObject[nameof(DACL)];
    /// <summary>
    /// ACE that identifies the trustee representing the group of the object.
    /// </summary>
    public _Object? Group => (_Object)ManagementObject[nameof(Group)];
    /// <summary>
    /// ACE that identifies the trustee representing the owner of the object.
    /// </summary>
    public _Object? Owner => (_Object)ManagementObject[nameof(Owner)];
    /// <summary>
    /// An array of __ACE entries that identifies users and groups for which auditing information is gathered.
    /// </summary>
    public _Object? SACL => (_Object)ManagementObject[nameof(SACL)];
    /// <summary>
    /// Time in the CIM_DATETIME format when the security descriptor was created.
    /// </summary>
    public ulong? TIME_CREATED => (ulong?)ManagementObject[nameof(TIME_CREATED)];
}
