/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Base;

public partial record class _TimerEvent(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Number of times the event occurred before a notification was delivered to the consumer.
    /// </summary>
    public uint? NumFirings => (uint?)ManagementObject[nameof(NumFirings)];
    /// <summary>
    /// Instance of the __TimerInstruction subclass that caused WMI to fire this event. Consumers specify a timer identification in the TimerId property of the __TimerInstruction subclass that they create to register.
    /// </summary>
    public string? TimerId => (string)ManagementObject[nameof(TimerId)];
}
