/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Base;

public partial record class _Trustee(ManagementObject ManagementObject) : _Object(ManagementObject)
{
    /// <summary>
    /// Domain portion of the account.
    /// </summary>
    public string? Domain => (string)ManagementObject[nameof(Domain)];
    /// <summary>
    /// Name portion of the account.
    /// </summary>
    public string? Name => (string)ManagementObject[nameof(Name)];
    /// <summary>
    /// The SID of the trustee in the binary byte array form.
    /// </summary>
    public byte[]? SID => (byte[])ManagementObject[nameof(SID)];
    /// <summary>
    /// The length of the SID in bytes.
    /// </summary>
    public uint? SidLength => (uint?)ManagementObject[nameof(SidLength)];
    /// <summary>
    /// The SID of the trustee in the string format, for example, "S-1-1-0".
    /// </summary>
    public string? SidString => (string)ManagementObject[nameof(SidString)];
    /// <summary>
    /// Time in the CIM_DATETIME format when the security descriptor was created.
    /// </summary>
    public ulong? TIME_CREATED => (ulong?)ManagementObject[nameof(TIME_CREATED)];
}
