/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

public partial record class AllocatedResource(ManagementObject ManagementObject) : Dependency(ManagementObject)
{
    /// <summary>
    /// A CIM_LogicalDevice that contains the logical device to which the resource is assigned.
    /// </summary>
    public new LogicalDevice? Dependent => (LogicalDevice)ManagementObject[nameof(Dependent)];
    /// <summary>
    /// A CIM_SystemResource that describes the resource.
    /// </summary>
    public new SystemResource? Antecedent => (SystemResource)ManagementObject[nameof(Antecedent)];
}
