/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

#nullable enable
public partial record class AssociatedProcessorMemory(ManagementObject ManagementObject) : AssociatedMemory(ManagementObject)
{
    /// <summary>
    /// A CIM_Processor describing the processor that accesses the memory or uses the cache.
    /// </summary>
    public new Processor? Dependent => (Processor)ManagementObject[nameof(Dependent)];
    /// <summary>
    /// Speed of the bus, in megahertz (MHz), between the processor and memory.
    /// </summary>
    public uint? BusSpeed => (uint?)ManagementObject[nameof(BusSpeed)];
}
#nullable disable
