/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

#nullable enable
public partial record class BasedOn(ManagementObject ManagementObject) : Dependency(ManagementObject)
{
    /// <summary>
    /// A CIM_StorageExtent that describes the higher level storage extent.
    /// </summary>
    public new StorageExtent? Dependent => (StorageExtent)ManagementObject[nameof(Dependent)];
    /// <summary>
    /// A CIM_StorageExtent that describes the lower level storage extent.
    /// </summary>
    public new StorageExtent? Antecedent => (StorageExtent)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// Indicates the end of the high-level extent in lower-level storage. This property is useful when mapping non-contiguous extents into a higher-level grouping.
    /// </summary>
    public ulong? EndingAddress => (ulong?)ManagementObject[nameof(EndingAddress)];
    /// <summary>
    /// Indicates the beginning of the high-level extent in lower-level storage.
    /// </summary>
    public ulong? StartingAddress => (ulong?)ManagementObject[nameof(StartingAddress)];
}
#nullable disable
