/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

#nullable enable
public partial record class Battery(ManagementObject ManagementObject) : LogicalDevice(ManagementObject)
{
    /// <summary>
    /// Description of the battery's charge status. The value 10 is not valid in the CIM schema, which represents no battery being installed in Desktop Management Interface (DMI). In this case, the object should not be instantiated.
    /// </summary>
    public ushort? BatteryStatus => (ushort?)ManagementObject[nameof(BatteryStatus)];
    /// <summary>
    /// Enumeration that describes the battery's chemistry.
    /// </summary>
    public ushort? Chemistry => (ushort?)ManagementObject[nameof(Chemistry)];
    /// <summary>
    /// Designed capacity of the battery in milliwatt-hours. If this property is not supported, enter 0.
    /// </summary>
    public uint? DesignCapacity => (uint?)ManagementObject[nameof(DesignCapacity)];
    /// <summary>
    /// Designed voltage of the battery in millivolts. If this attribute is not supported, enter 0.
    /// </summary>
    public ulong? DesignVoltage => (ulong?)ManagementObject[nameof(DesignVoltage)];
    /// <summary>
    /// Estimated percentage of the remaining full charge.
    /// </summary>
    public ushort? EstimatedChargeRemaining => (ushort?)ManagementObject[nameof(EstimatedChargeRemaining)];
    /// <summary>
    /// Estimated time, in minutes, until the battery charge is depleted under the present load conditions if the utility power is off, is lost and remains off, or if a laptop is disconnected from a power source.
    /// </summary>
    public uint? EstimatedRunTime => (uint?)ManagementObject[nameof(EstimatedRunTime)];
    /// <summary>
    /// Battery's expected lifetime, in minutes, assuming that the battery is fully charged. This property represents the total expected life of the battery, not its current remaining life, which is indicated by the EstimatedRunTime property.
    /// </summary>
    public uint? ExpectedLife => (uint?)ManagementObject[nameof(ExpectedLife)];
    /// <summary>
    /// The full charge capacity of the battery in milliwatt-hours. Compare this value to the DesignCapacity property to determine when the battery requires replacement. A battery's end-life is typically when the FullChargeCapacity property falls below 80 percent of the DesignCapacity property. If this property is not supported, enter 0.
    /// </summary>
    public uint? FullChargeCapacity => (uint?)ManagementObject[nameof(FullChargeCapacity)];
    /// <summary>
    /// Maximum time, in minutes, to fully charge the battery. This property represents the time to recharge a fully depleted battery, not the current remaining charging time, which is indicated in the TimeToFullCharge property.
    /// </summary>
    public uint? MaxRechargeTime => (uint?)ManagementObject[nameof(MaxRechargeTime)];
    /// <summary>
    /// Smart battery data-specification version number that is supported by this battery. If the battery does not support this function, the value should be left empty.
    /// </summary>
    public string? SmartBatteryVersion => (string)ManagementObject[nameof(SmartBatteryVersion)];
    /// <summary>
    /// Elapsed time, in seconds, since the computer system's UPS last switched to battery power, or the amount of time since the system or UPS was last restarted, whichever is less. A value of 0 is returned if the battery is "online."
    /// </summary>
    public uint? TimeOnBattery => (uint?)ManagementObject[nameof(TimeOnBattery)];
    /// <summary>
    /// Remaining time, in minutes, to charge the battery fully at the current charging rate and use.
    /// </summary>
    public uint? TimeToFullCharge => (uint?)ManagementObject[nameof(TimeToFullCharge)];
}
#nullable disable
