/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

public partial record class CDROMDrive(ManagementObject ManagementObject) : MediaAccessDevice(ManagementObject)
{
}
