/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class Chassis(ManagementObject ManagementObject) : PhysicalFrame(ManagementObject)
{
    /// <summary>
    /// Enumerated, integer-valued array that indicates the type of chassis.
    /// </summary>
    public ushort[]? ChassisTypes => (ushort[])ManagementObject[nameof(ChassisTypes)];
    /// <summary>
    /// Currently required by the chassis at 120 volts. If power is provided by the chassis (as in the case of a UPS), this property can indicate the amperage produced, as a negative number.
    /// </summary>
    public short? CurrentRequiredOrProduced => (short?)ManagementObject[nameof(CurrentRequiredOrProduced)];
    /// <summary>
    /// Amount of heat generated by the chassis in Btu/hour.
    /// </summary>
    public ushort? HeatGeneration => (ushort?)ManagementObject[nameof(HeatGeneration)];
    /// <summary>
    /// Number of power cords that must be connected to the chassis so that all of the components can operate.
    /// </summary>
    public ushort? NumberOfPowerCords => (ushort?)ManagementObject[nameof(NumberOfPowerCords)];
    /// <summary>
    /// Array of free-form strings that provides information about the ChassisTypes array entries.
    /// </summary>
    public string[]? TypeDescriptions => (string[])ManagementObject[nameof(TypeDescriptions)];
}
