/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

public partial record class Chip(ManagementObject ManagementObject) : PhysicalComponent(ManagementObject)
{
    /// <summary>
    /// Implementation form factor for the chip. The following values can be specified.
    /// </summary>
    public ushort? FormFactor => (ushort?)ManagementObject[nameof(FormFactor)];
}
