/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class Component(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// A CIM_ManagedSystemElement that describes the parent element in the association.
    /// </summary>
    public Base._Object? GroupComponent => (Base._Object)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// A CIM_ManagedSystemElement that describes the child element in the association.
    /// </summary>
    public Base._Object? PartComponent => (Base._Object)ManagementObject[nameof(PartComponent)];
}
