/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class ComputerSystemResource(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// A CIM_SystemResource that describes a system resource of the computer system.
    /// </summary>
    public Base._Object? PartComponent => (Base._Object)ManagementObject[nameof(PartComponent)];
    /// <summary>
    /// A CIM_ComputerSystem that describes the computer system.
    /// </summary>
    public Base._Object? GroupComponent => (Base._Object)ManagementObject[nameof(GroupComponent)];
}
