/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

#nullable enable
public partial record class DataFile(ManagementObject ManagementObject) : LogicalFile(ManagementObject)
{
    /// <summary>
    /// Manufacturer string from the version resource (if one is present).
    /// </summary>
    public string? Manufacturer => (string)ManagementObject[nameof(Manufacturer)];
    /// <summary>
    /// Version string from the version resource (if one is present).
    /// </summary>
    public string? Version => (string)ManagementObject[nameof(Version)];
}
#nullable disable
