/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class DesktopMonitor(ManagementObject ManagementObject) : Display(ManagementObject)
{
    /// <summary>
    /// Monitor's bandwidth in MHz. If unknown, use 0 (zero).
    /// </summary>
    public uint? Bandwidth => (uint?)ManagementObject[nameof(Bandwidth)];
    /// <summary>
    /// Type of desktop monitor or CRT.
    /// </summary>
    public ushort? DisplayType => (ushort?)ManagementObject[nameof(DisplayType)];
    /// <summary>
    /// Logical height of the display, in screen coordinates.
    /// </summary>
    public uint? ScreenHeight => (uint?)ManagementObject[nameof(ScreenHeight)];
    /// <summary>
    /// Logical width of the display, in screen coordinates.
    /// </summary>
    public uint? ScreenWidth => (uint?)ManagementObject[nameof(ScreenWidth)];
}
