/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class DiskPartition(ManagementObject ManagementObject) : StorageExtent(ManagementObject)
{
    /// <summary>
    /// If TRUE, the disk partition is labeled as bootable. This does not mean that an operating system is loaded on the partition.
    /// </summary>
    public bool? Bootable => (bool?)ManagementObject[nameof(Bootable)];
    /// <summary>
    /// If TRUE, the disk partition is labeled as the primary partition for a computer system.
    /// </summary>
    public bool? PrimaryPartition => (bool?)ManagementObject[nameof(PrimaryPartition)];
}
