/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

public partial record class ElementSetting(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the role of the CIM_ManagedSystemElement object of the CIM_ElementSetting association. The associated managed system element provides the element that implements the element setting.
    /// </summary>
    public ManagedSystemElement? Element => (ManagedSystemElement)ManagementObject[nameof(Element)];
    /// <summary>
    /// Reference to the role of the CIM_Setting object of the CIM_ElementSetting association. The associated setting provides the setting that implements the element setting.
    /// </summary>
    public Setting? Setting => (Setting)ManagementObject[nameof(Setting)];
}
