/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class IRQ(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Availability of the IRQ.
    /// </summary>
    public ushort? Availability => (ushort?)ManagementObject[nameof(Availability)];
    /// <summary>
    /// Name of the class or subclass used in the creation of an instance. When used with other key properties of the class, this property allows all instances of the class and its subclasses to be uniquely identified.
    /// </summary>
    public string? CreationClassName => (string)ManagementObject[nameof(CreationClassName)];
    /// <summary>
    /// Scoping computer system's creation class name.
    /// </summary>
    public string? CSCreationClassName => (string)ManagementObject[nameof(CSCreationClassName)];
    /// <summary>
    /// Scoping computer system's name.
    /// </summary>
    public string? CSName => (string)ManagementObject[nameof(CSName)];
    /// <summary>
    /// Part of the object's key value, IRQ number.
    /// </summary>
    public uint? IRQNumber => (uint?)ManagementObject[nameof(IRQNumber)];
    /// <summary>
    /// If TRUE, the IRQ can be shared.
    /// </summary>
    public bool? Shareable => (bool?)ManagementObject[nameof(Shareable)];
    /// <summary>
    /// Indicates whether the interruption is triggered by the hardware signal going high or low.
    /// </summary>
    public ushort? TriggerLevel => (ushort?)ManagementObject[nameof(TriggerLevel)];
    /// <summary>
    /// Type of interruption that can occur.
    /// </summary>
    public ushort? TriggerType => (ushort?)ManagementObject[nameof(TriggerType)];
}
