/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class Job(ManagementObject ManagementObject) : LogicalElement(ManagementObject)
{
    /// <summary>
    /// Length of time the job has been executing.
    /// </summary>
    public DateTimeOffset? ElapsedTime => ManagementObject.GetDateTimePropertyValue(nameof(ElapsedTime));
    /// <summary>
    /// Free-form string that represents the job status.
    /// </summary>
    public string? JobStatus => (string)ManagementObject[nameof(JobStatus)];
    /// <summary>
    /// User is notified upon job completion or failure.
    /// </summary>
    public string? Notify => (string)ManagementObject[nameof(Notify)];
    /// <summary>
    /// User who submitted the job.
    /// </summary>
    public string? Owner => (string)ManagementObject[nameof(Owner)];
    /// <summary>
    /// Importance of a job's execution.
    /// </summary>
    public uint? Priority => (uint?)ManagementObject[nameof(Priority)];
    /// <summary>
    /// Time that the job began.
    /// </summary>
    public DateTimeOffset? StartTime => ManagementObject.GetDateTimePropertyValue(nameof(StartTime));
    /// <summary>
    /// Time that the job was submitted.
    /// </summary>
    public DateTimeOffset? TimeSubmitted => ManagementObject.GetDateTimePropertyValue(nameof(TimeSubmitted));
    /// <summary>
    /// Time at which the job is invalid or should be stopped.
    /// </summary>
    public DateTimeOffset? UntilTime => ManagementObject.GetDateTimePropertyValue(nameof(UntilTime));
}
