/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

public partial record class Keyboard(ManagementObject ManagementObject) : UserDevice(ManagementObject)
{
    /// <summary>
    /// Free-form string that indicates the format and layout of the keyboard.
    /// </summary>
    public string? Layout => (string)ManagementObject[nameof(Layout)];
    /// <summary>
    /// Number of function keys on the keyboard.
    /// </summary>
    public ushort? NumberOfFunctionKeys => (ushort?)ManagementObject[nameof(NumberOfFunctionKeys)];
    /// <summary>
    /// Integer that indicates whether a hardware-level password is enabled on the keyboard to prevent local input.
    /// </summary>
    public ushort? Password => (ushort?)ManagementObject[nameof(Password)];
}
