/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class LogicalDisk(ManagementObject ManagementObject) : StorageExtent(ManagementObject)
{
    /// <summary>
    /// Available free space, in bytes, on the logical disk.
    /// </summary>
    public ulong? FreeSpace => (ulong?)ManagementObject[nameof(FreeSpace)];
    /// <summary>
    /// Size of the logical disk, in bytes.
    /// </summary>
    public ulong? Size => (ulong?)ManagementObject[nameof(Size)];
}
