/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class ManagedSystemElement(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// A short textual description of the object.
    /// </summary>
    public string? Caption => (string)ManagementObject[nameof(Caption)];
    /// <summary>
    /// A textual description of the object.
    /// </summary>
    public string? Description => (string)ManagementObject[nameof(Description)];
    /// <summary>
    /// Indicates when the object was installed. Lack of a value does not indicate that the object is not installed.
    /// </summary>
    public DateTimeOffset? InstallDate => ManagementObject.GetDateTimePropertyValue(nameof(InstallDate));
    /// <summary>
    /// Label by which the object is known. When subclassed, this property can be overridden to be a key property.
    /// </summary>
    public string? Name => (string)ManagementObject[nameof(Name)];
    /// <summary>
    /// String that indicates the current status of the object. Operational and non-operational status can be defined. Operational status can include "OK", "Degraded", and "Pred Fail". "Pred Fail" indicates that an element is functioning properly, but is predicting a failure (for example, a SMART-enabled hard disk drive).
    /// </summary>
    public string? Status => (string)ManagementObject[nameof(Status)];
}
