/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

#nullable enable
public partial record class MemoryMappedIO(ManagementObject ManagementObject) : SystemResource(ManagementObject)
{
    /// <summary>
    /// Name of the class or subclass used in the creation of an instance. When used with other key properties of the class, this property allows all instances of the class and its subclasses to be uniquely identified.
    /// </summary>
    public string? CreationClassName => (string)ManagementObject[nameof(CreationClassName)];
    /// <summary>
    /// Scoping computer system's CreationClassName property.
    /// </summary>
    public string? CSCreationClassName => (string)ManagementObject[nameof(CSCreationClassName)];
    /// <summary>
    /// Scoping computer system's Name property.
    /// </summary>
    public string? CSName => (string)ManagementObject[nameof(CSName)];
    /// <summary>
    /// Ending address of memory mapped I/O.
    /// </summary>
    public ulong? EndingAddress => (ulong?)ManagementObject[nameof(EndingAddress)];
    /// <summary>
    /// Starting address of memory mapped I/O. The hardware resource identifier property should be set to this value to construct the mapped I/O resource key.
    /// </summary>
    public ulong? StartingAddress => (ulong?)ManagementObject[nameof(StartingAddress)];
}
#nullable disable
