/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class NetworkAdapter(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// If TRUE, the network adapter can automatically determine the speed or other communications characteristics of the attached network media.
    /// </summary>
    public bool? AutoSense => (bool?)ManagementObject[nameof(AutoSense)];
    /// <summary>
    /// Maximum speed, in bits per second (BPS), for the network adapter.
    /// </summary>
    public ulong? MaxSpeed => (ulong?)ManagementObject[nameof(MaxSpeed)];
    /// <summary>
    /// List of network addresses for an adapter.
    /// </summary>
    public string[]? NetworkAddresses => (string[])ManagementObject[nameof(NetworkAddresses)];
    /// <summary>
    /// Network address hard-coded into an adapter. The hard-coded address can be changed with a firmware upgrade or software configuration. If changed, the field should be updated when the change is made. This property should be left blank if no hard-coded address exists for the network adapter.
    /// </summary>
    public string? PermanentAddress => (string)ManagementObject[nameof(PermanentAddress)];
    /// <summary>
    /// Estimate of the current bandwidth, in BPS. For endpoints that vary in bandwidth or for those where no accurate estimation can be made, this property should contain the nominal bandwidth.
    /// </summary>
    public ulong? Speed => (ulong?)ManagementObject[nameof(Speed)];
}
