/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class NumericSensor(ManagementObject ManagementObject) : Sensor(ManagementObject)
{
    /// <summary>
    /// Accuracy of the sensor for the measured property. Its value is recorded as plus or minus hundredths of a percent. This property, and the Resolution and Tolerance properties, are used to calculate the actual value of the measured physical property. Accuracy can vary depending on whether the device is linear over its dynamic range.
    /// </summary>
    public int? Accuracy => (int?)ManagementObject[nameof(Accuracy)];
    /// <summary>
    /// Current value indicated by the sensor.
    /// </summary>
    public int? CurrentReading => (int?)ManagementObject[nameof(CurrentReading)];
    /// <summary>
    /// If TRUE, the sensor is linear over its dynamic range.
    /// </summary>
    public bool? IsLinear => (bool?)ManagementObject[nameof(IsLinear)];
    /// <summary>
    /// Largest value of the measured property that can be read by the numeric sensor.
    /// </summary>
    public int? MaxReadable => (int?)ManagementObject[nameof(MaxReadable)];
    /// <summary>
    /// Smallest value of the measured property that can be read by the numeric sensor.
    /// </summary>
    public int? MinReadable => (int?)ManagementObject[nameof(MinReadable)];
    /// <summary>
    /// Expected or "normal" value for the numeric sensor.
    /// </summary>
    public int? NominalReading => (int?)ManagementObject[nameof(NominalReading)];
    /// <summary>
    /// Normal maximum range for the numeric sensor.
    /// </summary>
    public int? NormalMax => (int?)ManagementObject[nameof(NormalMax)];
    /// <summary>
    /// Normal minimum range for the numeric sensor.
    /// </summary>
    public int? NormalMin => (int?)ManagementObject[nameof(NormalMin)];
    /// <summary>
    /// Ability of the sensor to resolve differences in the measured property. This value may vary depending on whether the device is linear over its dynamic range.
    /// </summary>
    public uint? Resolution => (uint?)ManagementObject[nameof(Resolution)];
    /// <summary>
    /// Tolerance of the sensor for the measured property. This property, and the Resolution and Accuracy properties, are used to calculate the actual value of the measured physical property. Tolerance may vary depending on whether the device is linear over its dynamic range.
    /// </summary>
    public int? Tolerance => (int?)ManagementObject[nameof(Tolerance)];
}
