/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class PCVideoController(ManagementObject ManagementObject) : VideoController(ManagementObject)
{
    /// <summary>
    /// Current number of color planes. If this value is not applicable for the current video configuration, enter 0.
    /// </summary>
    public ushort? NumberOfColorPlanes => (ushort?)ManagementObject[nameof(NumberOfColorPlanes)];
    /// <summary>
    /// Video architecture.
    /// </summary>
    public ushort? VideoArchitecture => (ushort?)ManagementObject[nameof(VideoArchitecture)];
    /// <summary>
    /// Current video mode.
    /// </summary>
    public ushort? VideoMode => (ushort?)ManagementObject[nameof(VideoMode)];
}
