/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

#nullable enable
public partial record class PhysicalConnector(ManagementObject ManagementObject) : PhysicalElement(ManagementObject)
{
    /// <summary>
    /// Free-form string that describes the pin configuration and signal use of a physical connector.
    /// </summary>
    public string? ConnectorPinout => (string)ManagementObject[nameof(ConnectorPinout)];
    /// <summary>
    /// Type of physical connector. An array is specified to allow the description of combinations of connector information. For example, one array entry could specify RS-232, another DB-25, and a third entry could define the connector as "male".
    /// </summary>
    public ushort[]? ConnectorType => (ushort[])ManagementObject[nameof(ConnectorType)];
}
#nullable disable
