/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

public partial record class Processor(ManagementObject ManagementObject) : LogicalDevice(ManagementObject)
{
    /// <summary>
    /// Processor address width, in bits.
    /// </summary>
    public ushort? AddressWidth => (ushort?)ManagementObject[nameof(AddressWidth)];
    /// <summary>
    /// Current speed (in megahertz) of the processor.
    /// </summary>
    public uint? CurrentClockSpeed => (uint?)ManagementObject[nameof(CurrentClockSpeed)];
    /// <summary>
    /// Processor data width, in bits.
    /// </summary>
    public ushort? DataWidth => (ushort?)ManagementObject[nameof(DataWidth)];
    /// <summary>
    /// Loading of the processor, averaged over the last minute, in a percentage.
    /// </summary>
    public ushort? LoadPercentage => (ushort?)ManagementObject[nameof(LoadPercentage)];
    /// <summary>
    /// Maximum speed (in megahertz) of the processor.
    /// </summary>
    public uint? MaxClockSpeed => (uint?)ManagementObject[nameof(MaxClockSpeed)];
    /// <summary>
    /// Description of the processor family type. This property is used when the Family property is set to 1 ("Other"). This string should be set to null when the Family property is a value other than 1.
    /// </summary>
    public string? OtherFamilyDescription => (string)ManagementObject[nameof(OtherFamilyDescription)];
    /// <summary>
    /// Free-form string that describes the role of the processor. For example, "Central Processor" or "Math Processor".
    /// </summary>
    public string? Role => (string)ManagementObject[nameof(Role)];
    /// <summary>
    /// Free-form string that indicates the revision level of the processor within the processor family.
    /// </summary>
    public string? Stepping => (string)ManagementObject[nameof(Stepping)];
    /// <summary>
    /// Globally unique identifier for the processor. This identifier can only be unique within a processor family.
    /// </summary>
    public string? UniqueId => (string)ManagementObject[nameof(UniqueId)];
    /// <summary>
    /// CPU socket information, which includes data on how to upgrade the processor (if upgrades are supported).
    /// </summary>
    public ushort? UpgradeMethod => (ushort?)ManagementObject[nameof(UpgradeMethod)];
}
