/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

public partial record class Product(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Short textual description for the product.
    /// </summary>
    public string? Caption => (string)ManagementObject[nameof(Caption)];
    /// <summary>
    /// Textual description of the product.
    /// </summary>
    public string? Description => (string)ManagementObject[nameof(Description)];
    /// <summary>
    /// Product identification, such as a serial number on software, a die number on a hardware chip, or (for noncommercial products) a project number.
    /// </summary>
    public string? IdentifyingNumber => (string)ManagementObject[nameof(IdentifyingNumber)];
    /// <summary>
    /// Commonly used product name.
    /// </summary>
    public string? Name => (string)ManagementObject[nameof(Name)];
    /// <summary>
    /// Product's stock-keeping unit (SKU) information.
    /// </summary>
    public string? SKUNumber => (string)ManagementObject[nameof(SKUNumber)];
    /// <summary>
    /// Name of the product's supplier, or the entity selling the product (the manufacturer, reseller, OEM, and so on).
    /// </summary>
    public string? Vendor => (string)ManagementObject[nameof(Vendor)];
    /// <summary>
    /// Product version information.
    /// </summary>
    public string? Version => (string)ManagementObject[nameof(Version)];
}
