/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class Realizes(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// A CIM_LogicalDevice that describes the logical device.
    /// </summary>
    public Base._Object? Dependent => (Base._Object)ManagementObject[nameof(Dependent)];
    /// <summary>
    /// A CIM_PhysicalElement that describes the physical component that implements the device.
    /// </summary>
    public Base._Object? Antecedent => (Base._Object)ManagementObject[nameof(Antecedent)];
}
