/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class SCSIController(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Number of SCSI controller time-outs that have occurred since the last reset.
    /// </summary>
    public uint? ControllerTimeouts => (uint?)ManagementObject[nameof(ControllerTimeouts)];
    /// <summary>
    /// Maximum data width, in bits, supported by the SCSI controller.
    /// </summary>
    public uint? MaxDataWidth => (uint?)ManagementObject[nameof(MaxDataWidth)];
    /// <summary>
    /// Maximum transfer rate, in bits-per-second, supported by the SCSI controller.
    /// </summary>
    public ulong? MaxTransferRate => (ulong?)ManagementObject[nameof(MaxTransferRate)];
    /// <summary>
    /// Indicates whether the SCSI controller provides redundancy or protection against device failures.
    /// </summary>
    public ushort? ProtectionManagement => (ushort?)ManagementObject[nameof(ProtectionManagement)];
}
