/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class Service(ManagementObject ManagementObject) : LogicalElement(ManagementObject)
{
    /// <summary>
    /// Name of the class or subclass used in the creation of an instance. When used with other key properties of the class, this property allows all instances of the class and its subclasses to be uniquely identified.
    /// </summary>
    public string? CreationClassName => (string)ManagementObject[nameof(CreationClassName)];
    /// <summary>
    /// The Name property uniquely identifies the service and provides an indication of the functionality that is managed. This functionality is described in more detail in the object's Description property.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
    /// <summary>
    /// If TRUE, the service has started.
    /// </summary>
    public bool? Started => (bool?)ManagementObject[nameof(Started)];
    /// <summary>
    /// Indicates whether the service is automatically started (for example, by an operating system) or only started upon request.
    /// </summary>
    public string? StartMode => (string)ManagementObject[nameof(StartMode)];
    /// <summary>
    /// Scoping system's creation class name.
    /// </summary>
    public string? SystemCreationClassName => (string)ManagementObject[nameof(SystemCreationClassName)];
    /// <summary>
    /// Name of the system that hosts the service.
    /// </summary>
    public string? SystemName => (string)ManagementObject[nameof(SystemName)];
}
