/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class Slot(ManagementObject ManagementObject) : PhysicalConnector(ManagementObject)
{
    /// <summary>
    /// Maximum height, in inches, of an adapter card that can be inserted into the slot.
    /// </summary>
    public float? HeightAllowed => (float?)ManagementObject[nameof(HeightAllowed)];
    /// <summary>
    /// Maximum length, in inches, of an adapter card that can be inserted into the slot.
    /// </summary>
    public float? LengthAllowed => (float?)ManagementObject[nameof(LengthAllowed)];
    /// <summary>
    /// Maximum bus width, in bits, of adapter cards that can be inserted into the slot.
    /// </summary>
    public ushort? MaxDataWidth => (ushort?)ManagementObject[nameof(MaxDataWidth)];
    /// <summary>
    /// Physical slot number, which can be used as an index into a system slot table, to determine whether the slot is physically occupied.
    /// </summary>
    public ushort? Number => (ushort?)ManagementObject[nameof(Number)];
    /// <summary>
    /// Free-form string that describes how this slot is physically unique and that it may hold special types of hardware. This property only has meaning when the corresponding Boolean SpecialPurpose property is set to TRUE.
    /// </summary>
    public string? PurposeDescription => (string)ManagementObject[nameof(PurposeDescription)];
    /// <summary>
    /// If TRUE, the slot is physically unique and may hold special types of hardware, (for example, a graphics processor slot). If TRUE, the PurposeDescription property should specify how the slot is unique or the slot's purpose.
    /// </summary>
    public bool? SpecialPurpose => (bool?)ManagementObject[nameof(SpecialPurpose)];
    /// <summary>
    /// If TRUE, the slot supports hot-plugging of adapter cards.
    /// </summary>
    public bool? SupportsHotPlug => (bool?)ManagementObject[nameof(SupportsHotPlug)];
    /// <summary>
    /// Maximum thermal dissipation of the slot, in milliwatts.
    /// </summary>
    public uint? ThermalRating => (uint?)ManagementObject[nameof(ThermalRating)];
    /// <summary>
    /// Vcc voltage supported by the slot.
    /// </summary>
    public ushort[]? VccMixedVoltageSupport => (ushort[])ManagementObject[nameof(VccMixedVoltageSupport)];
    /// <summary>
    /// Vpp voltage supported by the slot.
    /// </summary>
    public ushort[]? VppMixedVoltageSupport => (ushort[])ManagementObject[nameof(VppMixedVoltageSupport)];
}
