/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class StatisticalInformation(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Short textual description for the statistic or metric.
    /// </summary>
    public string? Caption => (string)ManagementObject[nameof(Caption)];
    /// <summary>
    /// Textual description of the statistic or metric.
    /// </summary>
    public string? Description => (string)ManagementObject[nameof(Description)];
    /// <summary>
    /// Label by which the statistic or metric is known. When subclassed, this property can be overridden to be a key property.
    /// </summary>
    public string? Name => (string)ManagementObject[nameof(Name)];
}
