/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class SystemDevice(ManagementObject ManagementObject) : SystemComponent(ManagementObject)
{
    /// <summary>
    /// A CIM_LogicalDevice that describes the logical device that is a component of a system.
    /// </summary>
    public new Base._Object? PartComponent => (Base._Object)ManagementObject[nameof(PartComponent)];
    /// <summary>
    /// A CIM_System that describes the parent system in the association.
    /// </summary>
    public new Base._Object? GroupComponent => (Base._Object)ManagementObject[nameof(GroupComponent)];
}
