/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class SystemComponent(ManagementObject ManagementObject) : Component(ManagementObject)
{
    /// <summary>
    /// A CIM_ManagedSystemElement that describes the child element that is a component of a system.
    /// </summary>
    public new Base._Object? PartComponent => (Base._Object)ManagementObject[nameof(PartComponent)];
    /// <summary>
    /// A CIM_System that describes the parent system in the association.
    /// </summary>
    public new System? GroupComponent => (System)ManagementObject[nameof(GroupComponent)];
}
