/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

#nullable enable
public partial record class SystemDevice(ManagementObject ManagementObject) : SystemComponent(ManagementObject)
{
    /// <summary>
    /// A CIM_LogicalDevice that describes the logical device that is a component of a system.
    /// </summary>
    public new LogicalDevice? PartComponent => (LogicalDevice)ManagementObject[nameof(PartComponent)];
    /// <summary>
    /// A CIM_System that describes the parent system in the association.
    /// </summary>
    public new System? GroupComponent => (System)ManagementObject[nameof(GroupComponent)];
}
#nullable disable
