/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class TapeDrive(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Size, in bytes, of the area designated as end-of-tape. Access in this area generates an end-of-tape warning.
    /// </summary>
    public uint? EOTWarningZoneSize => (uint?)ManagementObject[nameof(EOTWarningZoneSize)];
    /// <summary>
    /// Maximum partition count for the tape drive.
    /// </summary>
    public uint? MaxPartitionCount => (uint?)ManagementObject[nameof(MaxPartitionCount)];
    /// <summary>
    /// Number of bytes inserted between blocks on a tape media.
    /// </summary>
    public uint? Padding => (uint?)ManagementObject[nameof(Padding)];
}
