/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.CIM;

#nullable enable
public partial record class USBController(ManagementObject ManagementObject) : Controller(ManagementObject)
{
    /// <summary>
    /// Name of the USB controller manufacturer.
    /// </summary>
    public string? Manufacturer => (string)ManagementObject[nameof(Manufacturer)];
}
#nullable disable
