/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.CIM;

public partial record class VideoControllerResolution(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// An ID that serves as part of the key for the current instance.
    /// </summary>
    public string? SettingID => (string)ManagementObject[nameof(SettingID)];
    /// <summary>
    /// Horizontal resolution, in pixels.
    /// </summary>
    public uint? HorizontalResolution => (uint?)ManagementObject[nameof(HorizontalResolution)];
    /// <summary>
    /// Maximum refresh rate when a range of rates is supported at the specified resolutions, in hertz.
    /// </summary>
    public uint? MaxRefreshRate => (uint?)ManagementObject[nameof(MaxRefreshRate)];
    /// <summary>
    /// Minimum refresh rate when a range of rates is supported at the specified resolutions, in hertz.
    /// </summary>
    public uint? MinRefreshRate => (uint?)ManagementObject[nameof(MinRefreshRate)];
    /// <summary>
    /// Number of colors supported at the current resolution.
    /// </summary>
    public ulong? NumberOfColors => (ulong?)ManagementObject[nameof(NumberOfColors)];
    /// <summary>
    /// Refresh rate, in hertz. If a range of rates is supported, use the MinRefreshRate and MaxRefreshRate properties, and set this property to 0.
    /// </summary>
    public uint? RefreshRate => (uint?)ManagementObject[nameof(RefreshRate)];
    /// <summary>
    /// Scan mode at which the controller operates.
    /// </summary>
    public ushort? ScanMode => (ushort?)ManagementObject[nameof(ScanMode)];
    /// <summary>
    /// Controller's vertical resolution, in pixels.
    /// </summary>
    public uint? VerticalResolution => (uint?)ManagementObject[nameof(VerticalResolution)];
}
