/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class Account(ManagementObject ManagementObject) : CIM.LogicalElement(ManagementObject)
{
    /// <summary>
    /// Name of the Windows domain to which a group or user belongs.
    /// </summary>
    public string? Domain => (string)ManagementObject[nameof(Domain)];
    /// <summary>
    /// If TRUE, the account is defined on the local machine. To retrieve only accounts defined on the local machine, design a query that includes the condition "LocalAccount=TRUE".
    /// </summary>
    public bool? LocalAccount => (bool?)ManagementObject[nameof(LocalAccount)];
    /// <summary>
    /// Name of the Windows system account on the domain specified by the Domain property of this class. This property overrides the Name property inherited from CIM_ManagedSystemElement.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
    /// <summary>
    /// Security identifier (SID) for this account. A SID is a string value of variable length used to identify a trustee. Each account has a unique SID issued by an authority (such as a Windows domain), stored in a security database. When a user logs on, the system retrieves the user's SID from the database and places it in the user's access token. The system uses the SID in the user's access token to identify the user in all subsequent interactions with Windows security. When a SID has been used as the unique identifier for a user or group, it cannot be used again to identify another user or group.
    /// </summary>
    public string? SID => (string)ManagementObject[nameof(SID)];
    /// <summary>
    /// Enumerated values that specify the type of security identifier (SID).
    /// </summary>
    public byte? SIDType => (byte?)ManagementObject[nameof(SIDType)];
}
