/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class AllocatedResource(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// A CIM_LogicalDevice that represents the properties of the logical device that is using the system resources assigned to it.
    /// </summary>
    public Base._Object? Dependent => (Base._Object)ManagementObject[nameof(Dependent)];
    /// <summary>
    /// A CIM_SystemResource that describes the properties of a system resource available to the logical device.
    /// </summary>
    public Base._Object? Antecedent => (Base._Object)ManagementObject[nameof(Antecedent)];
}
