/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class AutochkSetting(ManagementObject ManagementObject) : CIM.Setting(ManagementObject)
{
    /// <summary>
    /// An ID that is used as part of a key for the current object.
    /// </summary>
    public new string? SettingID => (string)ManagementObject[nameof(SettingID)];
    /// <summary>
    /// The user input delay for autocheck.
    /// </summary>
    public uint? UserInputDelay => (uint?)ManagementObject[nameof(UserInputDelay)];
}
