/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class BaseBoard(ManagementObject ManagementObject) : CIM.Card(ManagementObject)
{
    /// <summary>
    /// Array that represents the configuration of the jumpers and switches located on the baseboard.
    /// </summary>
    public string[]? ConfigOptions => (string[])ManagementObject[nameof(ConfigOptions)];
    /// <summary>
    /// Baseboard part number defined by the manufacturer.
    /// </summary>
    public string? Product => (string)ManagementObject[nameof(Product)];
}
