/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class Battery(ManagementObject ManagementObject) : CIM.Battery(ManagementObject)
{
    /// <summary>
    /// Time required to fully charge the battery. This property is not supported. BatteryRechargeTime does not have a replacement property, and is now considered obsolete.
    /// </summary>
    public uint? BatteryRechargeTime => (uint?)ManagementObject[nameof(BatteryRechargeTime)];
    /// <summary>
    /// Amount of time it takes to completely drain the battery after it is fully charged. This property is no longer used and is considered obsolete.
    /// </summary>
    public uint? ExpectedBatteryLife => (uint?)ManagementObject[nameof(ExpectedBatteryLife)];
}
