/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class BIOS(ManagementObject ManagementObject) : CIM.BIOSElement(ManagementObject)
{
    /// <summary>
    /// Array of BIOS characteristics supported by the system as defined by the System Management BIOS Reference Specification.
    /// </summary>
    public ushort[]? BiosCharacteristics => (ushort[])ManagementObject[nameof(BiosCharacteristics)];
    /// <summary>
    /// Array of the complete system BIOS information. In many computers there can be several version strings that are stored in the registry and represent the system BIOS information.
    /// </summary>
    public string[]? BIOSVersion => (string[])ManagementObject[nameof(BIOSVersion)];
    /// <summary>
    /// Name of the current BIOS language.
    /// </summary>
    public string? CurrentLanguage => (string)ManagementObject[nameof(CurrentLanguage)];
    /// <summary>
    /// The major release of the embedded controller firmware.
    /// </summary>
    public byte? EmbeddedControllerMajorVersion => (byte?)ManagementObject[nameof(EmbeddedControllerMajorVersion)];
    /// <summary>
    /// The minor release of the embedded controller firmware.
    /// </summary>
    public byte? EmbeddedControllerMinorVersion => (byte?)ManagementObject[nameof(EmbeddedControllerMinorVersion)];
    /// <summary>
    /// Number of languages available for installation on this system. Language may determine properties such as the need for Unicode and bidirectional text.
    /// </summary>
    public ushort? InstallableLanguages => (ushort?)ManagementObject[nameof(InstallableLanguages)];
    /// <summary>
    /// Array of names of available BIOS-installable languages.
    /// </summary>
    public string[]? ListOfLanguages => (string[])ManagementObject[nameof(ListOfLanguages)];
    /// <summary>
    /// Release date of the Windows BIOS in the Coordinated Universal Time (UTC) format of YYYYMMDDHHMMSS.MMMMMM(+-)OOO.
    /// </summary>
    public DateTimeOffset? ReleaseDate => ManagementObject.GetDateTimePropertyValue(nameof(ReleaseDate));
    /// <summary>
    /// BIOS version as reported by SMBIOS.
    /// </summary>
    public string? SMBIOSBIOSVersion => (string)ManagementObject[nameof(SMBIOSBIOSVersion)];
    /// <summary>
    /// Major SMBIOS version number. This property is NULL if SMBIOS is not found.
    /// </summary>
    public ushort? SMBIOSMajorVersion => (ushort?)ManagementObject[nameof(SMBIOSMajorVersion)];
    /// <summary>
    /// Minor SMBIOS version number. This property is NULL if SMBIOS is not found.
    /// </summary>
    public ushort? SMBIOSMinorVersion => (ushort?)ManagementObject[nameof(SMBIOSMinorVersion)];
    /// <summary>
    /// If true, the SMBIOS is available on this computer system.
    /// </summary>
    public bool? SMBIOSPresent => (bool?)ManagementObject[nameof(SMBIOSPresent)];
    /// <summary>
    /// The major release of the System BIOS.
    /// </summary>
    public byte? SystemBiosMajorVersion => (byte?)ManagementObject[nameof(SystemBiosMajorVersion)];
    /// <summary>
    /// The minor release of the System BIOS.
    /// </summary>
    public byte? SystemBiosMinorVersion => (byte?)ManagementObject[nameof(SystemBiosMinorVersion)];
}
