/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class Bus(ManagementObject ManagementObject) : CIM.LogicalDevice(ManagementObject)
{
    /// <summary>
    /// Logical number assigned to the physical bus.
    /// </summary>
    public uint? BusNum => (uint?)ManagementObject[nameof(BusNum)];
    /// <summary>
    /// Type of the physical bus. This value will be one of the values in the INTERFACE_TYPE enumeration defined in Bus.h.
    /// </summary>
    public uint? BusType => (uint?)ManagementObject[nameof(BusType)];
}
