/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class CDROMDrive(ManagementObject ManagementObject) : CIM.CDROMDrive(ManagementObject)
{
    /// <summary>
    /// Drive letter of the CD-ROM drive.
    /// </summary>
    public string? Drive => (string)ManagementObject[nameof(Drive)];
    /// <summary>
    /// If True, files can be accurately read from the CD device. This is achieved by reading a block of data twice and comparing the data against itself.
    /// </summary>
    public bool? DriveIntegrity => (bool?)ManagementObject[nameof(DriveIntegrity)];
    /// <summary>
    /// This property is obsolete. In place of this property, use FileSystemFlagsEx.
    /// </summary>
    public ushort? FileSystemFlags => (ushort?)ManagementObject[nameof(FileSystemFlags)];
    /// <summary>
    /// File system flags associated with the Windows CD-ROM drive. This parameter can be any combination of flags, but FS_FILE_COMPRESSION and FS_VOL_IS_COMPRESSED are mutually exclusive.
    /// </summary>
    public uint? FileSystemFlagsEx => (uint?)ManagementObject[nameof(FileSystemFlagsEx)];
    /// <summary>
    /// Drive letter that uniquely identifies this CD-ROM drive.
    /// </summary>
    public string? Id => (string)ManagementObject[nameof(Id)];
    /// <summary>
    /// Manufacturer of the Windows CD-ROM drive.
    /// </summary>
    public string? Manufacturer => (string)ManagementObject[nameof(Manufacturer)];
    /// <summary>
    /// Maximum length of a filename component supported by the Windows CD-ROM drive. A file name component the portion of a file name between backslashes. The value can be used to indicate that long names are supported by the specified file system. For example, for a FAT file system supporting long names, the function stores the value 255, rather than the previous 8.3 indicator. Long names can also be supported on systems that use the NTFS file system.
    /// </summary>
    public uint? MaximumComponentLength => (uint?)ManagementObject[nameof(MaximumComponentLength)];
    /// <summary>
    /// If True, a CD-ROM is in the drive.
    /// </summary>
    public bool? MediaLoaded => (bool?)ManagementObject[nameof(MediaLoaded)];
    public string? MediaType => (string)ManagementObject[nameof(MediaType)];
    /// <summary>
    /// Firmware revision level that is assigned by the manufacturer.
    /// </summary>
    public string? MfrAssignedRevisionLevel => (string)ManagementObject[nameof(MfrAssignedRevisionLevel)];
    /// <summary>
    /// Firmware revision level of the Windows CD-ROM drive.
    /// </summary>
    public string? RevisionLevel => (string)ManagementObject[nameof(RevisionLevel)];
    /// <summary>
    /// SCSI bus number for the disk drive.
    /// </summary>
    public uint? SCSIBus => (uint?)ManagementObject[nameof(SCSIBus)];
    /// <summary>
    /// SCSI logical unit number (LUN) of the disk drive. The LUN is used to designate which SCSI controller is being accessed in a system with more than one controller being used. The SCSI device identifier is similar, but is the designation for multiple devices on one controller.
    /// </summary>
    public ushort? SCSILogicalUnit => (ushort?)ManagementObject[nameof(SCSILogicalUnit)];
    /// <summary>
    /// SCSI port number of the disk drive.
    /// </summary>
    public ushort? SCSIPort => (ushort?)ManagementObject[nameof(SCSIPort)];
    /// <summary>
    /// SCSI identifier number of the Windows CD-ROM drive.
    /// </summary>
    public ushort? SCSITargetId => (ushort?)ManagementObject[nameof(SCSITargetId)];
    public string? SerialNumber => (string)ManagementObject[nameof(SerialNumber)];
    /// <summary>
    /// Size of the disk drive.
    /// </summary>
    public ulong? Size => (ulong?)ManagementObject[nameof(Size)];
    /// <summary>
    /// Transfer rate of the CD-ROM drive. A value of -1 indicates that the rate cannot be determined. When this happens, the CD is not in the drive.
    /// </summary>
    public double? TransferRate => (double?)ManagementObject[nameof(TransferRate)];
    /// <summary>
    /// Volume name of the Windows CD-ROM drive.
    /// </summary>
    public string? VolumeName => (string)ManagementObject[nameof(VolumeName)];
    /// <summary>
    /// Volume serial number of the media in the CD-ROM drive.
    /// </summary>
    public string? VolumeSerialNumber => (string)ManagementObject[nameof(VolumeSerialNumber)];
}
