/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class ClassicCOMClassSettings(ManagementObject ManagementObject) : CIM.ElementSetting(ManagementObject)
{
    /// <summary>
    /// A Win32_ClassicCOMClassSetting that represents configuration settings associated with the COM class.
    /// </summary>
    public new ClassicCOMClassSetting? Setting => (ClassicCOMClassSetting)ManagementObject[nameof(Setting)];
    /// <summary>
    /// A Win32_ClassicCOMClass that represents the COM class where the settings are applied.
    /// </summary>
    public new ClassicCOMClass? Element => (ClassicCOMClass)ManagementObject[nameof(Element)];
}
#nullable disable
