/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class ClassicCOMClass(ManagementObject ManagementObject) : COMClass(ManagementObject)
{
    /// <summary>
    /// Globally unique identifier (GUID) of this COM class.
    /// </summary>
    public string? ComponentId => (string)ManagementObject[nameof(ComponentId)];
    /// <summary>
    /// The Name property contains the human-readable name for the COM class.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
}
