/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class ClassicCOMApplicationClasses(ManagementObject ManagementObject) : COMApplicationClasses(ManagementObject)
{
    /// <summary>
    /// A Win32_ClassicCOMClass that represents the COM component existing in or used by the DCOM application.
    /// </summary>
    public new ClassicCOMClass? PartComponent => (ClassicCOMClass)ManagementObject[nameof(PartComponent)];
    /// <summary>
    /// A Win32_DCOMApplication that represents a DCOM application containing or using the COM component.
    /// </summary>
    public new DCOMApplication? GroupComponent => (DCOMApplication)ManagementObject[nameof(GroupComponent)];
}
#nullable disable
