/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class ClassicCOMClassSettings(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// A Win32_ClassicCOMClassSetting that represents configuration settings associated with the COM class.
    /// </summary>
    public Base._Object? Setting => (Base._Object)ManagementObject[nameof(Setting)];
    /// <summary>
    /// A Win32_ClassicCOMClass that represents the COM class where the settings are applied.
    /// </summary>
    public Base._Object? Element => (Base._Object)ManagementObject[nameof(Element)];
}
