/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class ClientApplicationSetting(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the instance that represents the COM application that contains configuration options of the executable file.
    /// </summary>
    public Base._Object? Application => (Base._Object)ManagementObject[nameof(Application)];
    /// <summary>
    /// Reference to the instance that represents the executable file that uses COM settings.
    /// </summary>
    public Base._Object? Client => (Base._Object)ManagementObject[nameof(Client)];
}
