/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class ClientApplicationSetting(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the instance that represents the COM application that contains configuration options of the executable file.
    /// </summary>
    public DCOMApplication? Application => (DCOMApplication)ManagementObject[nameof(Application)];
    /// <summary>
    /// Reference to the instance that represents the executable file that uses COM settings.
    /// </summary>
    public CIM.DataFile? Client => (CIM.DataFile)ManagementObject[nameof(Client)];
}
#nullable disable
