/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class ClusterShare(ManagementObject ManagementObject) : Share(ManagementObject)
{
    /// <summary>
    /// The cluster server on which the share is hosted.
    /// </summary>
    public string? ServerName => (string)ManagementObject[nameof(ServerName)];
}
