/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class COMApplication(ManagementObject ManagementObject) : CIM.LogicalElement(ManagementObject)
{
}
