/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class ComClassAutoEmulator(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the COM component that can automatically emulate the associated COM component. This information is obtained through the AutoTreatAs registry entry.
    /// </summary>
    public Base._Object? NewVersion => (Base._Object)ManagementObject[nameof(NewVersion)];
    /// <summary>
    /// Reference to the instance representing the COM component that is automatically emulated by another component.
    /// </summary>
    public Base._Object? OldVersion => (Base._Object)ManagementObject[nameof(OldVersion)];
}
