/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class ComputerSystemProduct(ManagementObject ManagementObject) : CIM.Product(ManagementObject)
{
    /// <summary>
    /// Universally unique identifier (UUID) for this product. A UUID is a 128-bit identifier that is guaranteed to be different from other generated UUIDs. If a UUID is not available, a UUID of all zeros is used.
    /// </summary>
    public string? UUID => (string)ManagementObject[nameof(UUID)];
}
#nullable disable
