/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class ComputerSystemProcessor(ManagementObject ManagementObject) : SystemDevices(ManagementObject)
{
    /// <summary>
    /// A Win32_Processor that describes the properties of a processor which is running the computer system.
    /// </summary>
    public new Base._Object? PartComponent => (Base._Object)ManagementObject[nameof(PartComponent)];
    /// <summary>
    /// A Win32_ComputerSystem that describes the properties of the computer system on which the processor is running.
    /// </summary>
    public new Base._Object? GroupComponent => (Base._Object)ManagementObject[nameof(GroupComponent)];
}
