/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class ComponentCategory(ManagementObject ManagementObject) : CIM.LogicalElement(ManagementObject)
{
    /// <summary>
    /// GUID for this component category.
    /// </summary>
    public string? CategoryId => (string)ManagementObject[nameof(CategoryId)];
    /// <summary>
    /// The Name property indicates a descriptive name of this component category.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
}
