/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class DCOMApplication(ManagementObject ManagementObject) : COMApplication(ManagementObject)
{
    /// <summary>
    /// Globally unique identifier (GUID) for the DCOM application.
    /// </summary>
    public string? AppID => (string)ManagementObject[nameof(AppID)];
}
#nullable disable
