/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class DiskDriveToDiskPartition(ManagementObject ManagementObject) : CIM.MediaPresent(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the properties of the disk drive where the partition exists.
    /// </summary>
    public new Base._Object? Antecedent => (Base._Object)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// Reference to the instance representing the disk partition residing on the disk drive.
    /// </summary>
    public new Base._Object? Dependent => (Base._Object)ManagementObject[nameof(Dependent)];
}
