/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class DMAChannel(ManagementObject ManagementObject) : CIM.DMA(ManagementObject)
{
    /// <summary>
    /// DMA port used by the host bus adapter. This is meaningful for MCA-type buses.
    /// </summary>
    public uint? Port => (uint?)ManagementObject[nameof(Port)];
}
