/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class Environment(ManagementObject ManagementObject) : CIM.SystemResource(ManagementObject)
{
    /// <summary>
    /// Character string that specifies the name of a Windows-based environment variable. By specifying the name of a variable that does not yet exist, an application creates a new environment variable.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
    /// <summary>
    /// Indicates whether the variable is a system variable. A system variable is set by the operating system, and is independent from user environment settings.
    /// </summary>
    public bool? SystemVariable => (bool?)ManagementObject[nameof(SystemVariable)];
    /// <summary>
    /// Name of the owner of the environment setting. It is set to &lt;SYSTEM&gt; for settings that are specific to the Windows-based system (as opposed to a specific user) and &lt;DEFAULT&gt; for default user settings.
    /// </summary>
    public string? UserName => (string)ManagementObject[nameof(UserName)];
    /// <summary>
    /// Placeholder variable of a Windows-based environment variable. Information like the file system directory can change from computer to computer. The operating system substitutes placeholders for these.
    /// </summary>
    public string? VariableValue => (string)ManagementObject[nameof(VariableValue)];
}
