/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class GroupUser(ManagementObject ManagementObject) : CIM.Component(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the group of which the account is a member.
    /// </summary>
    public new Group? GroupComponent => (Group)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// Reference to the instance representing the user or system account that is a part of a group of accounts.
    /// </summary>
    public new Account? PartComponent => (Account)ManagementObject[nameof(PartComponent)];
}
