/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class IDEControllerDevice(ManagementObject ManagementObject) : CIM.ControlledBy(ManagementObject)
{
    /// <summary>
    /// A Win32_IDEController that represents the IDE controller associated with this device.
    /// </summary>
    public new IDEController? Antecedent => (IDEController)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// A CIM_LogicalDevice that represents the logical device connected to the IDE controller.
    /// </summary>
    public new CIM.LogicalDevice? Dependent => (CIM.LogicalDevice)ManagementObject[nameof(Dependent)];
}
