/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class ImplementedCategory(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the component category being used by the COM class.
    /// </summary>
    public Base._Object? Category => (Base._Object)ManagementObject[nameof(Category)];
    /// <summary>
    /// Reference to the instance representing the COM class using the associated category.
    /// </summary>
    public Base._Object? Component => (Base._Object)ManagementObject[nameof(Component)];
}
