/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class LoadOrderGroup(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Indicates whether this load order group can include drivers along with system services.
    /// </summary>
    public bool? DriverEnabled => (bool?)ManagementObject[nameof(DriverEnabled)];
    /// <summary>
    /// Sequence in which this group of services is loaded onto the operating system.
    /// </summary>
    public uint? GroupOrder => (uint?)ManagementObject[nameof(GroupOrder)];
    /// <summary>
    /// Name of the load order group.
    /// </summary>
    public string? Name => (string)ManagementObject[nameof(Name)];
}
