/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class LogicalProgramGroupDirectory(ManagementObject ManagementObject) : CIM.Dependency(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the logical program group.
    /// </summary>
    public new LogicalProgramGroup? Antecedent => (LogicalProgramGroup)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// Reference to the instance representing the file directory for the logical program group.
    /// </summary>
    public new Directory? Dependent => (Directory)ManagementObject[nameof(Dependent)];
}
#nullable disable
