/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class LogicalProgramGroup(ManagementObject ManagementObject) : ProgramGroupOrItem(ManagementObject)
{
    /// <summary>
    /// Name of the Windows program group. Program groups are implemented as file folders in Win32.
    /// </summary>
    public string? GroupName => (string)ManagementObject[nameof(GroupName)];
    /// <summary>
    /// User-assigned name followed by the group name. Program groups are implemented as file folders in Win32.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
    /// <summary>
    /// Users who can access the Windows program group. Program groups are implemented as file folders in Win32.
    /// </summary>
    public string? UserName => (string)ManagementObject[nameof(UserName)];
}
