/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class LogicalProgramGroupItemDataFile(ManagementObject ManagementObject) : CIM.Dependency(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the program groupings in the Start menu.
    /// </summary>
    public new LogicalProgramGroupItem? Antecedent => (LogicalProgramGroupItem)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// Reference to the instance representing the class associated with the program group.
    /// </summary>
    public new CIM.DataFile? Dependent => (CIM.DataFile)ManagementObject[nameof(Dependent)];
}
#nullable disable
