/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class LogonSession(ManagementObject ManagementObject) : Session(ManagementObject)
{
    /// <summary>
    /// Name of the subsystem used to authenticate the logon session.
    /// </summary>
    public string? AuthenticationPackage => (string)ManagementObject[nameof(AuthenticationPackage)];
    /// <summary>
    /// ID assigned to the logon session.
    /// </summary>
    public string? LogonId => (string)ManagementObject[nameof(LogonId)];
    /// <summary>
    /// Numeric value that indicates the type of logon session.
    /// </summary>
    public uint? LogonType => (uint?)ManagementObject[nameof(LogonType)];
}
