/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class MotherboardDevice(ManagementObject ManagementObject) : CIM.LogicalDevice(ManagementObject)
{
    /// <summary>
    /// Primary bus type of the motherboard.
    /// </summary>
    public string? PrimaryBusType => (string)ManagementObject[nameof(PrimaryBusType)];
    /// <summary>
    /// Revision number of the motherboard.
    /// </summary>
    public string? RevisionNumber => (string)ManagementObject[nameof(RevisionNumber)];
    /// <summary>
    /// Secondary bus type of the motherboard.
    /// </summary>
    public string? SecondaryBusType => (string)ManagementObject[nameof(SecondaryBusType)];
}
