/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class NetworkClient(ManagementObject ManagementObject) : CIM.LogicalElement(ManagementObject)
{
    /// <summary>
    /// Name of the manufacturer of the network client running on the computer system running Windows.
    /// </summary>
    public string? Manufacturer => (string)ManagementObject[nameof(Manufacturer)];
    /// <summary>
    /// Network name of the network client running on the computer system running Windows.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
}
