/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class OnBoardDevice(ManagementObject ManagementObject) : CIM.PhysicalComponent(ManagementObject)
{
    /// <summary>
    /// Type of device being represented.
    /// </summary>
    public ushort? DeviceType => (ushort?)ManagementObject[nameof(DeviceType)];
    /// <summary>
    /// If TRUE, the on-board device is available for use.
    /// </summary>
    public bool? Enabled => (bool?)ManagementObject[nameof(Enabled)];
}
