/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class OperatingSystemAutochkSetting(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// TBD
    /// </summary>
    public Base._Object? Element => (Base._Object)ManagementObject[nameof(Element)];
    /// <summary>
    /// TBD
    /// </summary>
    public Base._Object? Setting => (Base._Object)ManagementObject[nameof(Setting)];
}
