/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class OperatingSystemQFE(ManagementObject ManagementObject) : CIM.Dependency(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the system affected by the product update in this association.
    /// </summary>
    public new OperatingSystem? Antecedent => (OperatingSystem)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// Reference to the instance representing the object instance applied to the operating system in this association.
    /// </summary>
    public new QuickFixEngineering? Dependent => (QuickFixEngineering)ManagementObject[nameof(Dependent)];
}
