/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class OptionalFeature(ManagementObject ManagementObject) : CIM.LogicalElement(ManagementObject)
{
    /// <summary>
    /// An optional feature display name.
    /// </summary>
    public new string? Caption => (string)ManagementObject[nameof(Caption)];
    /// <summary>
    /// Represents the name of the optional feature.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
    public uint? InstallState => (uint?)ManagementObject[nameof(InstallState)];
}
