/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class OptionalFeature(ManagementObject ManagementObject) : CIM.LogicalElement(ManagementObject)
{
    /// <summary>
    /// An optional feature display name.
    /// </summary>
    public new string? Caption => (string)ManagementObject[nameof(Caption)];
    /// <summary>
    /// Represents the name of the optional feature.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
    public uint? InstallState => (uint?)ManagementObject[nameof(InstallState)];
}
#nullable disable
