/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class PageFileSetting(ManagementObject ManagementObject) : CIM.Setting(ManagementObject)
{
    /// <summary>
    /// Initial size of the page file.
    /// </summary>
    public uint? InitialSize => (uint?)ManagementObject[nameof(InitialSize)];
    /// <summary>
    /// Maximum size of the page file.
    /// </summary>
    public uint? MaximumSize => (uint?)ManagementObject[nameof(MaximumSize)];
    /// <summary>
    /// Path and file name of the page file.
    /// </summary>
    public string? Name => (string)ManagementObject[nameof(Name)];
}
#nullable disable
