/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class PCMCIAController(ManagementObject ManagementObject) : CIM.PCMCIAController(ManagementObject)
{
    /// <summary>
    /// Unique identifier of this device with other peripherals using the Plug and Play BIOS. This property is derived from CIM_LogicalDevice.
    /// </summary>
    public new string? DeviceID => (string)ManagementObject[nameof(DeviceID)];
}
