/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class PhysicalMemoryArray(ManagementObject ManagementObject) : CIM.PhysicalPackage(ManagementObject)
{
    /// <summary>
    /// Physical location of the memory array.
    /// </summary>
    public ushort? Location => (ushort?)ManagementObject[nameof(Location)];
    /// <summary>
    /// Use the MaxCapacityEx property instead.
    /// </summary>
    public uint? MaxCapacity => (uint?)ManagementObject[nameof(MaxCapacity)];
    /// <summary>
    /// Maximum memory size (in kilobytes) installable for this particular memory array. If the size is unknown, the property is given a value of 0 (zero).
    /// </summary>
    public ulong? MaxCapacityEx => (ulong?)ManagementObject[nameof(MaxCapacityEx)];
    /// <summary>
    /// Number of physical slots or sockets available in this memory array.
    /// </summary>
    public ushort? MemoryDevices => (ushort?)ManagementObject[nameof(MemoryDevices)];
    /// <summary>
    /// Type of error correction used by the memory array.
    /// </summary>
    public ushort? MemoryErrorCorrection => (ushort?)ManagementObject[nameof(MemoryErrorCorrection)];
    /// <summary>
    /// How memory is used in the computer system.
    /// </summary>
    public ushort? Use => (ushort?)ManagementObject[nameof(Use)];
}
