/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class PnPDevicePropertyDateTimeArray(ManagementObject ManagementObject) : PnPDeviceProperty(ManagementObject)
{
    /// <summary>
    /// The property value.
    /// </summary>
    public DateTimeOffset[]? Data => ManagementObject.GetDateTimePropertyValues(nameof(Data));
}
