/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class PnPDevicePropertySint8Array(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// The property value.
    /// </summary>
    public sbyte[]? Data => (sbyte[])ManagementObject[nameof(Data)];
}
