/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class PnPDevicePropertySint64Array(ManagementObject ManagementObject) : PnPDeviceProperty(ManagementObject)
{
    /// <summary>
    /// The property value.
    /// </summary>
    public long[]? Data => (long[])ManagementObject[nameof(Data)];
}
#nullable disable
