/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class PnPDevice(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the CIM_LogicalDevice instance representing the logical device properties associated with the Plug and Play device.
    /// </summary>
    public CIM.LogicalDevice? SameElement => (CIM.LogicalDevice)ManagementObject[nameof(SameElement)];
    /// <summary>
    /// Reference to the Win32_PnPEntity instance representing the Plug and Play device associated with the logical device.
    /// </summary>
    public PnPEntity? SystemElement => (PnPEntity)ManagementObject[nameof(SystemElement)];
}
