/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class PnPDevicePropertyUint16(ManagementObject ManagementObject) : PnPDeviceProperty(ManagementObject)
{
    /// <summary>
    /// The property value.
    /// </summary>
    public ushort? Data => (ushort?)ManagementObject[nameof(Data)];
}
