/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class PrinterDriver(ManagementObject ManagementObject) : CIM.Service(ManagementObject)
{
    /// <summary>
    /// Configuration file for this printer driver.
    /// </summary>
    public string? ConfigFile => (string)ManagementObject[nameof(ConfigFile)];
    /// <summary>
    /// Data file for this printer driver.
    /// </summary>
    public string? DataFile => (string)ManagementObject[nameof(DataFile)];
    /// <summary>
    /// Default data type for this printer driver.
    /// </summary>
    public string? DefaultDataType => (string)ManagementObject[nameof(DefaultDataType)];
    /// <summary>
    /// Array of dependent files for this printer driver.
    /// </summary>
    public string[]? DependentFiles => (string[])ManagementObject[nameof(DependentFiles)];
    /// <summary>
    /// Path for this printer driver.
    /// </summary>
    public string? DriverPath => (string)ManagementObject[nameof(DriverPath)];
    /// <summary>
    /// Path to the INF file being used.
    /// </summary>
    public string? FilePath => (string)ManagementObject[nameof(FilePath)];
    /// <summary>
    /// Help file for this printer driver.
    /// </summary>
    public string? HelpFile => (string)ManagementObject[nameof(HelpFile)];
    /// <summary>
    /// Name of the INF file being used. The default is to use an operating system provided printer INF file. A different file name is used if the driver is provided directly by the manufacturer of the printer and not the operating system.
    /// </summary>
    public string? InfName => (string)ManagementObject[nameof(InfName)];
    /// <summary>
    /// Name of the monitor for this printer driver.
    /// </summary>
    public string? MonitorName => (string)ManagementObject[nameof(MonitorName)];
    /// <summary>
    /// World Wide Web (WWW) link to the printer manufacturer's website. Note that this property is not populated when the Win32.inf file is used, and is only applicable for drivers provided directly from the manufacturer.
    /// </summary>
    public string? OEMUrl => (string)ManagementObject[nameof(OEMUrl)];
    /// <summary>
    /// Operating environments that the driver is intended for.
    /// </summary>
    public string? SupportedPlatform => (string)ManagementObject[nameof(SupportedPlatform)];
    /// <summary>
    /// Operating system version for the printer driver.
    /// </summary>
    public ushort? Version => (ushort?)ManagementObject[nameof(Version)];
}
#nullable disable
