/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class PrinterShare(ManagementObject ManagementObject) : CIM.Dependency(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the local printer shared in this association.
    /// </summary>
    public new Printer? Antecedent => (Printer)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// Reference to the instance representing the share of the printer in this association.
    /// </summary>
    public new Share? Dependent => (Share)ManagementObject[nameof(Dependent)];
}
