/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class PrivilegesStatus(ManagementObject ManagementObject) : Base._ExtendedStatus(ManagementObject)
{
    /// <summary>
    /// Listing required access privileges missing to complete an operation. The types of access privileges can be found under the Windows Privileges.
    /// </summary>
    public string[]? PrivilegesNotHeld => (string[])ManagementObject[nameof(PrivilegesNotHeld)];
    /// <summary>
    /// Listing of all of the privileges required to perform an operation. This includes values from the PrivilegesNotHeld property.
    /// </summary>
    public string[]? PrivilegesRequired => (string[])ManagementObject[nameof(PrivilegesRequired)];
}
