/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SCSIController(ManagementObject ManagementObject) : CIM.SCSIController(ManagementObject)
{
    /// <summary>
    /// Order in which the devices are listed with this SCSI controller.
    /// </summary>
    public string? DeviceMap => (string)ManagementObject[nameof(DeviceMap)];
    /// <summary>
    /// Driver file name of the SCSI controller.
    /// </summary>
    public string? DriverName => (string)ManagementObject[nameof(DriverName)];
    /// <summary>
    /// Hardware version number of the SCSI controller.
    /// </summary>
    public string? HardwareVersion => (string)ManagementObject[nameof(HardwareVersion)];
    /// <summary>
    /// Index number of the SCSI controller in the system registry.
    /// </summary>
    public uint? Index => (uint?)ManagementObject[nameof(Index)];
    /// <summary>
    /// Name of the SCSI controller manufacturer.
    /// </summary>
    public string? Manufacturer => (string)ManagementObject[nameof(Manufacturer)];
}
