/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SerialPortSetting(ManagementObject ManagementObject) : DeviceSettings(ManagementObject)
{
    /// <summary>
    /// A Win32_SerialPortConfiguration that contains the configuration setting for the serial port.
    /// </summary>
    public new SerialPortConfiguration? Setting => (SerialPortConfiguration)ManagementObject[nameof(Setting)];
    /// <summary>
    /// A Win32_SerialPort that contains the properties of a serial port on the computer system.
    /// </summary>
    public new SerialPort? Element => (SerialPort)ManagementObject[nameof(Element)];
}
