/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SerialPortSetting(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// A Win32_SerialPortConfiguration that contains the configuration setting for the serial port.
    /// </summary>
    public Base._Object? Setting => (Base._Object)ManagementObject[nameof(Setting)];
    /// <summary>
    /// A Win32_SerialPort that contains the properties of a serial port on the computer system.
    /// </summary>
    public Base._Object? Element => (Base._Object)ManagementObject[nameof(Element)];
}
