/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class SessionProcess(ManagementObject ManagementObject) : SessionResource(ManagementObject)
{
    /// <summary>
    /// A Win32_LogonSession that represents the session which is related to the process.
    /// </summary>
    public new LogonSession? Antecedent => (LogonSession)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// A Win32_Process that represents the process associated with the session.
    /// </summary>
    public new Process? Dependent => (Process)ManagementObject[nameof(Dependent)];
}
#nullable disable
