/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SessionProcess(ManagementObject ManagementObject) : SessionResource(ManagementObject)
{
    /// <summary>
    /// A Win32_LogonSession that represents the session which is related to the process.
    /// </summary>
    public new Base._Object? Antecedent => (Base._Object)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// A Win32_Process that represents the process associated with the session.
    /// </summary>
    public new Base._Object? Dependent => (Base._Object)ManagementObject[nameof(Dependent)];
}
