/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class ShortcutFile(ManagementObject ManagementObject) : CIM.DataFile(ManagementObject)
{
    /// <summary>
    /// Name of the object that this is a shortcut to.
    /// </summary>
    public string? Target => (string)ManagementObject[nameof(Target)];
}
#nullable disable
