/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class SubDirectory(ManagementObject ManagementObject) : CIM.Component(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the properties of the parent directory (folder) in this association.
    /// </summary>
    public new Directory? GroupComponent => (Directory)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// Reference to the instance representing the subdirectory (subfolder) part of the association.
    /// </summary>
    public new Directory? PartComponent => (Directory)ManagementObject[nameof(PartComponent)];
}
