/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SystemLoadOrderGroups(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the computer system where the load order group exists.
    /// </summary>
    public Base._Object? GroupComponent => (Base._Object)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// Reference to the instance representing the load order group existing on the computer system.
    /// </summary>
    public Base._Object? PartComponent => (Base._Object)ManagementObject[nameof(PartComponent)];
}
