/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SystemUsers(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the computer system containing the user account.
    /// </summary>
    public Base._Object? GroupComponent => (Base._Object)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// Reference to the instance representing the user account on the computer system.
    /// </summary>
    public UserAccount? PartComponent => (UserAccount)ManagementObject[nameof(PartComponent)];
}
