/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class SystemBIOS(ManagementObject ManagementObject) : CIM.SystemComponent(ManagementObject)
{
    /// <summary>
    /// A Win32_BIOS contained in the computer system of this association.
    /// </summary>
    public new BIOS? PartComponent => (BIOS)ManagementObject[nameof(PartComponent)];
    /// <summary>
    /// The Win32_ComputerSystem containing the BIOS of the association.
    /// </summary>
    public new ComputerSystem? GroupComponent => (ComputerSystem)ManagementObject[nameof(GroupComponent)];
}
#nullable disable
