/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SystemSystemDriver(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the properties of the computer system upon which the driver is running.
    /// </summary>
    public Base._Object? GroupComponent => (Base._Object)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// Reference to the instance representing the system driver running on the computer system.
    /// </summary>
    public Base._Object? PartComponent => (Base._Object)ManagementObject[nameof(PartComponent)];
}
