/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class SystemProgramGroups(ManagementObject ManagementObject) : SystemSetting(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the computer system containing the logical program group.
    /// </summary>
    public new ComputerSystem? Element => (ComputerSystem)ManagementObject[nameof(Element)];
    /// <summary>
    /// Reference to the instance representing the logical program group on the computer system.
    /// </summary>
    public new LogicalProgramGroup? Setting => (LogicalProgramGroup)ManagementObject[nameof(Setting)];
}
