/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SystemBootConfiguration(ManagementObject ManagementObject) : SystemSetting(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the computer system using the boot configuration.
    /// </summary>
    public new ComputerSystem? Element => (ComputerSystem)ManagementObject[nameof(Element)];
    /// <summary>
    /// Reference to the instance representing the boot configuration for the computer system.
    /// </summary>
    public new BootConfiguration? Setting => (BootConfiguration)ManagementObject[nameof(Setting)];
}
