/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SystemResources(ManagementObject ManagementObject) : CIM.ComputerSystemResource(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the computer system where the resource is located.
    /// </summary>
    public new ComputerSystem? GroupComponent => (ComputerSystem)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// Reference to the instance representing the resource (such as I/O services and memory resources) available on the computer system.
    /// </summary>
    public new CIM.SystemResource? PartComponent => (CIM.SystemResource)ManagementObject[nameof(PartComponent)];
}
