/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class SystemPartitions(ManagementObject ManagementObject) : SystemDevices(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the properties of the computer system where the disk partition is located.
    /// </summary>
    public new ComputerSystem? GroupComponent => (ComputerSystem)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// Reference to the instance representing the properties of a disk partition that exists on the computer system.
    /// </summary>
    public new DiskPartition? PartComponent => (DiskPartition)ManagementObject[nameof(PartComponent)];
}
