/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SystemProgramGroups(ManagementObject ManagementObject) : Base._Object(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the computer system containing the logical program group.
    /// </summary>
    public Base._Object? Element => (Base._Object)ManagementObject[nameof(Element)];
    /// <summary>
    /// Reference to the instance representing the logical program group on the computer system.
    /// </summary>
    public Base._Object? Setting => (Base._Object)ManagementObject[nameof(Setting)];
}
