/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class SystemLoadOrderGroups(ManagementObject ManagementObject) : CIM.SystemComponent(ManagementObject)
{
    /// <summary>
    /// Reference to the instance representing the computer system where the load order group exists.
    /// </summary>
    public new ComputerSystem? GroupComponent => (ComputerSystem)ManagementObject[nameof(GroupComponent)];
    /// <summary>
    /// Reference to the instance representing the load order group existing on the computer system.
    /// </summary>
    public new LoadOrderGroup? PartComponent => (LoadOrderGroup)ManagementObject[nameof(PartComponent)];
}
