/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                    *
 *   System.Management.Generator.                              *
 *   Any changes made to this file will be overwritten.        *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

#nullable enable
public partial record class SystemDriverPNPEntity(ManagementObject ManagementObject) : CIM.Dependency(ManagementObject)
{
    /// <summary>
    /// Represents the Plug and Play device controlled by the driver.
    /// </summary>
    public new PnPEntity? Antecedent => (PnPEntity)ManagementObject[nameof(Antecedent)];
    /// <summary>
    /// A Win32_SystemDriver that represents the driver that supports the Plug and Play device.
    /// </summary>
    public new SystemDriver? Dependent => (SystemDriver)ManagementObject[nameof(Dependent)];
}
#nullable disable
