/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class SystemAccount(ManagementObject ManagementObject) : Account(ManagementObject)
{
    /// <summary>
    /// Name of the Windows domain to which the system account belongs.
    /// </summary>
    public new string? Domain => (string)ManagementObject[nameof(Domain)];
    /// <summary>
    /// Name of the Windows system account on the domain specified by the Domain property of this class.
    /// </summary>
    public new string? Name => (string)ManagementObject[nameof(Name)];
}
