/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class TCPIPPrinterPort(ManagementObject ManagementObject) : CIM.ServiceAccessPoint(ManagementObject)
{
    /// <summary>
    /// If TRUE, the computer counts the bytes in a document before sending them to the printer and the printer reports back the number of bytes actually read. This capability is used for diagnostics when missing bytes are detected in the print output.
    /// </summary>
    public bool? ByteCount => (bool?)ManagementObject[nameof(ByteCount)];
    /// <summary>
    /// Address of the device or print server.
    /// </summary>
    public string? HostAddress => (string)ManagementObject[nameof(HostAddress)];
    /// <summary>
    /// Number of the TCP ports used by the port monitor to communicate with the device.
    /// </summary>
    public uint? PortNumber => (uint?)ManagementObject[nameof(PortNumber)];
    /// <summary>
    /// Printing protocol used. Some printers support only LPR.
    /// </summary>
    public uint? Protocol => (uint?)ManagementObject[nameof(Protocol)];
    /// <summary>
    /// Name of the print queue on the server when used with the LPR protocol.
    /// </summary>
    public string? Queue => (string)ManagementObject[nameof(Queue)];
    /// <summary>
    /// Security level value for the device.
    /// </summary>
    public string? SNMPCommunity => (string)ManagementObject[nameof(SNMPCommunity)];
    /// <summary>
    /// SNMP index number of this device for the SNMP agent.
    /// </summary>
    public uint? SNMPDevIndex => (uint?)ManagementObject[nameof(SNMPDevIndex)];
    /// <summary>
    /// If TRUE, this printer supports RFC 1759 (Simple Network Management Protocol) and can provide rich status information from the device.
    /// </summary>
    public bool? SNMPEnabled => (bool?)ManagementObject[nameof(SNMPEnabled)];
}
