/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class TimeZone(ManagementObject ManagementObject) : CIM.Setting(ManagementObject)
{
    public int? Bias => (int?)ManagementObject[nameof(Bias)];
    /// <summary>
    /// Bias value to be used during local time translations that occur during daylight saving time. This property is ignored if a value for the DaylightDay property is not supplied. The value of this property is added to the Bias property to form the bias used during daylight time. In most time zones, the value of this property is -60.
    /// </summary>
    public int? DaylightBias => (int?)ManagementObject[nameof(DaylightBias)];
    /// <summary>
    /// DaylightDayOfWeek of the DaylightMonth when the transition from standard time to daylight saving time occurs on this operating system.
    /// </summary>
    public uint? DaylightDay => (uint?)ManagementObject[nameof(DaylightDay)];
    /// <summary>
    /// Day of the week when the transition from standard time to daylight saving time occurs on an operating system.
    /// </summary>
    public byte? DaylightDayOfWeek => (byte?)ManagementObject[nameof(DaylightDayOfWeek)];
    /// <summary>
    /// Hour of the day when the transition from standard time to daylight saving time occurs on an operating system.
    /// </summary>
    public uint? DaylightHour => (uint?)ManagementObject[nameof(DaylightHour)];
    /// <summary>
    /// Millisecond of the DaylightSecond when the transition from standard time to daylight saving time occurs on an operating system.
    /// </summary>
    public uint? DaylightMillisecond => (uint?)ManagementObject[nameof(DaylightMillisecond)];
    /// <summary>
    /// Minute of the DaylightHour when the transition from standard time to daylight saving time occurs on an operating system.
    /// </summary>
    public uint? DaylightMinute => (uint?)ManagementObject[nameof(DaylightMinute)];
    /// <summary>
    /// Month when the transition from standard time to daylight saving time occurs on an operating system.
    /// </summary>
    public uint? DaylightMonth => (uint?)ManagementObject[nameof(DaylightMonth)];
    /// <summary>
    /// Time zone being represented when daylight saving time is in effect.
    /// </summary>
    public string? DaylightName => (string)ManagementObject[nameof(DaylightName)];
    /// <summary>
    /// Second of the DaylightMinute when the transition from standard time to daylight saving time occurs on an operating system.
    /// </summary>
    public uint? DaylightSecond => (uint?)ManagementObject[nameof(DaylightSecond)];
    /// <summary>
    /// Year when daylight saving time is in effect. This property is not required.
    /// </summary>
    public uint? DaylightYear => (uint?)ManagementObject[nameof(DaylightYear)];
    /// <summary>
    /// Bias value to use when daylight saving time is not in effect. This property is ignored if a value for StandardDay is not supplied. The value of this property is added to the Bias property to form the bias during standard time.
    /// </summary>
    public uint? StandardBias => (uint?)ManagementObject[nameof(StandardBias)];
    /// <summary>
    /// StandardDayOfWeek of the StandardMonth when the transition from daylight saving time to standard time occurs on an operating system.
    /// </summary>
    public uint? StandardDay => (uint?)ManagementObject[nameof(StandardDay)];
    /// <summary>
    /// Day of the week when the transition from daylight saving time to standard time occurs on an operating system.
    /// </summary>
    public byte? StandardDayOfWeek => (byte?)ManagementObject[nameof(StandardDayOfWeek)];
    /// <summary>
    /// Hour of the day when the transition from daylight saving time to standard time occurs on an operating system.
    /// </summary>
    public uint? StandardHour => (uint?)ManagementObject[nameof(StandardHour)];
    /// <summary>
    /// Millisecond of the StandardSecond when the transition from daylight saving time to standard time occurs on an operating system.
    /// </summary>
    public uint? StandardMillisecond => (uint?)ManagementObject[nameof(StandardMillisecond)];
    /// <summary>
    /// Minute of the StandardDay when the transition from daylight saving time to standard time occurs on an operating system.
    /// </summary>
    public uint? StandardMinute => (uint?)ManagementObject[nameof(StandardMinute)];
    /// <summary>
    /// Month when the transition from daylight saving time to standard time occurs on an operating system.
    /// </summary>
    public uint? StandardMonth => (uint?)ManagementObject[nameof(StandardMonth)];
    /// <summary>
    /// Name of the time zone being represented when standard time is in effect.
    /// </summary>
    public string? StandardName => (string)ManagementObject[nameof(StandardName)];
    /// <summary>
    /// Second of the StandardMinute when the transition from daylight saving time to standard time occurs on an operating system.
    /// </summary>
    public uint? StandardSecond => (uint?)ManagementObject[nameof(StandardSecond)];
    /// <summary>
    /// Year when standard time is in effect. This property is not required.
    /// </summary>
    public uint? StandardYear => (uint?)ManagementObject[nameof(StandardYear)];
}
