/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class UserAccount(ManagementObject ManagementObject) : Account(ManagementObject)
{
    /// <summary>
    /// Flags that describe the characteristics of a Windows user account.
    /// </summary>
    public uint? AccountType => (uint?)ManagementObject[nameof(AccountType)];
    /// <summary>
    /// Windows user account is disabled.
    /// </summary>
    public bool? Disabled => (bool?)ManagementObject[nameof(Disabled)];
    public new string? Domain => (string)ManagementObject[nameof(Domain)];
    public string? FullName => (string)ManagementObject[nameof(FullName)];
    /// <summary>
    /// If true, the user account is locked out of the Windows operating system.
    /// </summary>
    public bool? Lockout => (bool?)ManagementObject[nameof(Lockout)];
    /// <summary>
    /// If true, the password on this user account can be changed.
    /// </summary>
    public bool? PasswordChangeable => (bool?)ManagementObject[nameof(PasswordChangeable)];
    /// <summary>
    /// If true, the password on this user account expires.
    /// </summary>
    public bool? PasswordExpires => (bool?)ManagementObject[nameof(PasswordExpires)];
    /// <summary>
    /// If true, a password is required on a Windows user account. If false, this account does not require a password.
    /// </summary>
    public bool? PasswordRequired => (bool?)ManagementObject[nameof(PasswordRequired)];
}
