/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
namespace System.Management.Types.Win32;

public partial record class VideoSettings(ManagementObject ManagementObject) : CIM.VideoSetting(ManagementObject)
{
    /// <summary>
    /// A CIM_VideoControllerResolution containing settings that can be applied to the video controller.
    /// </summary>
    public new CIM.VideoControllerResolution? Setting => (CIM.VideoControllerResolution)ManagementObject[nameof(Setting)];
    /// <summary>
    /// A Win32_VideoController containing the properties of the video controller that a video setting can be used on.
    /// </summary>
    public new VideoController? Element => (VideoController)ManagementObject[nameof(Element)];
}
