/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class VideoSettings(ManagementObject ManagementObject) : CIM.VideoSetting(ManagementObject)
{
    /// <summary>
    /// A CIM_VideoControllerResolution containing settings that can be applied to the video controller.
    /// </summary>
    public new Base._Object? Setting => (Base._Object)ManagementObject[nameof(Setting)];
    /// <summary>
    /// A Win32_VideoController containing the properties of the video controller that a video setting can be used on.
    /// </summary>
    public new Base._Object? Element => (Base._Object)ManagementObject[nameof(Element)];
}
