/**************************************************************
 *                                                            *
 *   WARNING: This file is autogenerated by                   *
 *   System.Management.Generator.                             *
 *   Any changes made to this file will be overwritten.       *
 *                                                            *
 **************************************************************/
#nullable enable
namespace System.Management.Types.Win32;

public partial record class VolumeChangeEvent(ManagementObject ManagementObject) : DeviceChangeEvent(ManagementObject)
{
    /// <summary>
    /// Drive name (letter) that has been added or removed from the system.
    /// </summary>
    public string? DriveName => (string)ManagementObject[nameof(DriveName)];
}
