name: PR Type Generation

on:
  pull_request:
    paths:
      - 'Generator/*.*'
      - 'Types/**/*.g.cs'
      - '.github/workflows/generate-types-pr.yml'

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run generator
        run: dotnet run --project Generator/System.Management.Generator.csproj

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Types/**/*.g.cs
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes to PR branch
        if: steps.git-check.outputs.no_changes == 'false'
        run: |
          git commit -m "chore(types): update generated types (PR auto-update)"
          git push